import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const nunioSans = Nunito_Sans({
 weight: ["300", "600", "800"],
 subsets: ["latin"],
 variable: "--font-nunio_sans",
});

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
  <html lang="en">
   <body className={`${nunioSans.className} bg-lightGray text-primary`}>
    <Header />
    <main className="container py-6 sm:py-14">{children}</main>
   </body>
  </html>
 );
}
